/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './daterangepicker.module';
import * as i2 from './config.service';
export const DaterangepickerNgFactory:i0.NgModuleFactory<i1.Daterangepicker> = i0.ɵcmf(i1.Daterangepicker,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.DaterangepickerConfig,i2.DaterangepickerConfig,([] as any[])),i0.ɵmpd(512,
          i1.Daterangepicker,i1.Daterangepicker,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NyaWphbi9Eb2N1bWVudHMvdW50aXRsZWQgZm9sZGVyL25nMi1kYXRlcmFuZ2VwaWNrZXIvc3JjL2FwcC9kYXRlcmFuZ2VwaWNrZXIvZGF0ZXJhbmdlcGlja2VyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zcmlqYW4vRG9jdW1lbnRzL3VudGl0bGVkIGZvbGRlci9uZzItZGF0ZXJhbmdlcGlja2VyL3NyYy9hcHAvZGF0ZXJhbmdlcGlja2VyL2RhdGVyYW5nZXBpY2tlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
